platform :ios, '15.0'

target 'StandardCyborgTest' do
  use_frameworks!
 
  pod 'StandardCyborgFusion'
  pod 'StandardCyborgUI'
  pod 'Moya'
end

post_install do |installer|
  # Strip bitcode from precompiled StandardCyborgFusion framework
  bitcode_strip_path = `xcrun --find bitcode_strip`.strip
  framework_path = File.join(Dir.pwd, "Pods/StandardCyborgFusion/ios/StandardCyborgFusion.framework/StandardCyborgFusion")
  if File.exist?(framework_path)
    puts "Stripping bitcode from: #{framework_path}"
    system("#{bitcode_strip_path} '#{framework_path}' -r -o '#{framework_path}'")
  else
    puts "Warning: StandardCyborgFusion not found at #{framework_path}"
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
    end
  end
end